on:
  push:
    tags:
    - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'longer-upipes_${{steps.vars.outputs.tag}}.zip'
          exclusions: '*.git* README.md screenshot.png'
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: longer-upipes_${{steps.vars.outputs.tag}}.zip